title: "LEADx Docs"
remote_theme: pmarsceill/just-the-docs

footer_content: "Copyright &copy; 2021 LEADx. Distributed by an <a href=\"https://github.com/leadxhq/docs/blob/main/LICENSE\">MIT license.</a>"

ga_tracking: UA-93127621-1

gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/leadxhq/docs"
gh_edit_branch: "main"
gh_edit_view_mode: "edit"


search_enabled: true